@HOST=http://localhost:8080

###
GET {{HOST}}/ai?prompt=Hi

###
GET {{HOST}}/ai/stream?prompt=Hi

###
GET {{HOST}}/ai?prompt=Hi I'm Samit

###
GET {{HOST}}/ai?prompt=Who am I?

###
GET {{HOST}}/1/ai?prompt=Hi I'm Samit

###
GET {{HOST}}/1/ai?prompt=Who am I?

###
GET {{HOST}}/2/ai?prompt=Hi&voice=super angry man