
spring:
  application:
    name: spring-ai-all-in-one
  ai:
    azure:
      openai:
        api-key: ${API_KEY:fake}
        endpoint: ${ENDPOINT:fake}
        chat:
          options:
            deployment-name: gpt-4o-mini


management:
  endpoints:
    web:
      exposure:
        include: '*'
